########## PRANAY #############
##### File to filter just avg times from txt generated by automate.py
from builtins import open

f = open("rb_tree.txt", "r")
# f = open("bs_tree.txt","r")
lines = f.readlines()
# print(lines)

f.close()
f = open("rb_treeFiltered.txt", "a")
# f= open("bs_treeFiltered.txt","a")
for line in lines:
    if(line.find("trees")>0):
        f.write(line[line.find("es")+3:line.find(" 1")+2]+"\n")

for line in lines:
    if(line.find("):")>0):
        f.write(line[line.find("Real")+5:line.find("avg(")]+"\n")

f.close()